//
//  TransactionsInteractor.swift
//  BankUXS
//
//  Created by Carlos Colmenares on 1/10/18.
//  Copyright (c) 2018 Carlos Colmenares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionsBusinessLogic
{
  func doSomething(request: Transactions.Something.Request)
}

protocol TransactionsDataStore
{
  //var name: String { get set }
}

class TransactionsInteractor: TransactionsBusinessLogic, TransactionsDataStore
{
  var presenter: TransactionsPresentationLogic?
  var worker: TransactionsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Transactions.Something.Request)
  {
    worker = TransactionsWorker()
    worker?.doSomeWork()
    
    let response = Transactions.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
